resources:
  repositories:
  - repository: DotNetApplication # The name used to reference this repository in the checkout step
    type: github
    endpoint: vijishankar
    name: vijishankar/-
    trigger:
    - master

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: DotNetApplication

- script: dir $(Build.SourcesDirectory)
- script: cd $(Build.SourcesDirectory)/DotNetApplication
- script: ls
