resources:
  repositories:
  - repository: azureyaml # The name used to reference this repository in the checkout step
    type: github
    endpoint: vijishankar
    name: vijishankar/azureyaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: azureyaml

- script: dir $(Build.SourcesDirectory)