resources:
  repositories:
  - repository: DotNetApplication # The name used to reference this repository in the checkout step
    type: github
    endpoint: vijishankar
    name: Devtestproject/DotNetApplication
    ref: master

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: DotNetApplication

- script: dir $(Build.SourcesDirectory)
