resources:
  repositories:
  - repository: angular-ui # The name used to reference this repository in the checkout step
    type: github
    endpoint: vijishankar
    name: vijishankar/angular-ui

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)
